// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7qmHh_NwyRSwm1CwZo1VvlSDSYykOS9w',
    appId: '1:799017485209:web:712cdbf17ceea1b0dc4908',
    messagingSenderId: '799017485209',
    projectId: 'ecommerce-app-with-flutter',
    authDomain: 'ecommerce-app-with-flutter.firebaseapp.com',
    storageBucket: 'ecommerce-app-with-flutter.appspot.com',
    measurementId: 'G-V3THT8LEGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-d36tEv-h6lh4lBN2kwB_uRGaBRmuGX4',
    appId: '1:799017485209:android:0a792db701cd6f19dc4908',
    messagingSenderId: '799017485209',
    projectId: 'ecommerce-app-with-flutter',
    storageBucket: 'ecommerce-app-with-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL8ryuqEaYBTpHBvA1ReJZm1c_Puqg3kg',
    appId: '1:799017485209:ios:455d35483e6592addc4908',
    messagingSenderId: '799017485209',
    projectId: 'ecommerce-app-with-flutter',
    storageBucket: 'ecommerce-app-with-flutter.appspot.com',
    iosBundleId: 'com.ecommerce.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL8ryuqEaYBTpHBvA1ReJZm1c_Puqg3kg',
    appId: '1:799017485209:ios:455d35483e6592addc4908',
    messagingSenderId: '799017485209',
    projectId: 'ecommerce-app-with-flutter',
    storageBucket: 'ecommerce-app-with-flutter.appspot.com',
    iosBundleId: 'com.ecommerce.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7qmHh_NwyRSwm1CwZo1VvlSDSYykOS9w',
    appId: '1:799017485209:web:2aa47e74cd63048fdc4908',
    messagingSenderId: '799017485209',
    projectId: 'ecommerce-app-with-flutter',
    authDomain: 'ecommerce-app-with-flutter.firebaseapp.com',
    storageBucket: 'ecommerce-app-with-flutter.appspot.com',
    measurementId: 'G-51GNWSKMJJ',
  );

}